spring:
  application:
    name: crm-backend

  datasource:
    url: jdbc:h2:mem:crm_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-expiration-ms: 900000
  refresh-expiration-ms: 604800000